name: wifi-connect 
version: 0.10-1
summary: Connect your device to external wifi over temp wifi AP
description: |
  A solution to enable your device to connect to ian external
  wifi AP using a temporary wifi AP the device puts up and then
  opening its web portal. Note that wifi-connect daemon assumes
  control of device network management and other management solutions
  should not be simultaneously used.
  Please find the source of this snap at:
  https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/wifi-connect
grade: stable
confinement: strict

apps:
  wifi-connect: 
    command: cmd 
    plugs: [network, network-bind, network-manager, control]
  daemon:
    command: service 
    daemon: simple
    plugs: [network-manager, control, network-bind]

plugs:
  control:
    interface: content
    content: socket-directory
    target: $SNAP_COMMON/sockets
    default-provider: wifi-ap

parts:
  go:
    plugin: go
    source: . 
    go-importpath: launchpad.net/wifi-connect
    build-packages:
      # needed by go get
      - bzr
    install: |
      export GOPATH=$PWD/../go
      cd $GOPATH/src/launchpad.net/wifi-connect
      ./run-checks all
  assets:
    plugin: dump
    source: .
    stage:
      - static

